name: Run Tests on Pull Request

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm test
      - run: pnpm tsc
      - run: pnpm build
